-- MySQL Script generated by MySQL Workbench
-- qua 05 jul 2017 23:37:00 -03
-- Model: SCCE Modelo    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SCCE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SCCE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SCCE` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `SCCE` ;

-- -----------------------------------------------------
-- Table `SCCE`.`Grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE`.`Grupos` (
  `grup_id` INT NOT NULL AUTO_INCREMENT,
  `grup_nome` VARCHAR(45) NOT NULL,
  `grup_descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`grup_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCCE`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE`.`Funcionarios` (
  `func_id` INT NOT NULL AUTO_INCREMENT,
  `func_nome` VARCHAR(100) NOT NULL,
  `func_senha` VARCHAR(45) NULL,
  `func_salario` FLOAT NOT NULL,
  `func_grup_id` INT NOT NULL,
  PRIMARY KEY (`func_id`),
  INDEX `fk_Funcionarios_Categorias1_idx` (`func_grup_id` ASC),
  CONSTRAINT `fk_Funcionarios_Categorias1`
    FOREIGN KEY (`func_grup_id`)
    REFERENCES `SCCE`.`Grupos` (`grup_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'A chave estrangeira não está como obrigatório porque a princípio não iremos implementar o layer em amarelo.';


-- -----------------------------------------------------
-- Table `SCCE`.`Fabricantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE`.`Fabricantes` (
  `fabr_id` INT NOT NULL AUTO_INCREMENT,
  `fabr_nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`fabr_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCCE`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE`.`Produtos` (
  `prod_id` INT NOT NULL AUTO_INCREMENT,
  `prod_nome` VARCHAR(100) NOT NULL,
  `prod_quantidade` INT NOT NULL DEFAULT 0,
  `prod_preco_compra` FLOAT NOT NULL,
  `prod_preco_venda` FLOAT NOT NULL,
  `prod_fabr_id` INT NOT NULL,
  PRIMARY KEY (`prod_id`),
  INDEX `fk_Produtos_Fabricantes_idx` (`prod_fabr_id` ASC),
  CONSTRAINT `fk_Produtos_Fabricantes`
    FOREIGN KEY (`prod_fabr_id`)
    REFERENCES `SCCE`.`Fabricantes` (`fabr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCCE`.`Caixas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE`.`Caixas` (
  `caix_id` INT NOT NULL AUTO_INCREMENT,
  `caix_saldo` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`caix_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCCE`.`Turnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE`.`Turnos` (
  `turn_func_id` INT NOT NULL,
  `turn_caix_id` INT NOT NULL,
  `turn_horario_inicio` DATETIME NOT NULL,
  `turn_horario_fim` DATETIME NULL,
  PRIMARY KEY (`turn_func_id`, `turn_caix_id`, `turn_horario_inicio`),
  INDEX `fk_Funcionarios_has_Caixas_Caixas1_idx` (`turn_caix_id` ASC),
  INDEX `fk_Funcionarios_has_Caixas_Funcionarios1_idx` (`turn_func_id` ASC),
  CONSTRAINT `fk_Funcionarios_has_Caixas_Funcionarios1`
    FOREIGN KEY (`turn_func_id`)
    REFERENCES `SCCE`.`Funcionarios` (`func_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionarios_has_Caixas_Caixas1`
    FOREIGN KEY (`turn_caix_id`)
    REFERENCES `SCCE`.`Caixas` (`caix_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCCE`.`Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE`.`Compras` (
  `comp_id` INT NOT NULL,
  `comp_caix_id` INT NOT NULL,
  `comp_prod_id` INT NOT NULL,
  `comp_qtd_produto` INT NOT NULL,
  `comp_horario` DATETIME NULL,
  `comp_func_id` INT NULL,
  PRIMARY KEY (`comp_id`, `comp_caix_id`, `comp_prod_id`),
  INDEX `fk_Caixas_has_Produtos_Produtos1_idx` (`comp_prod_id` ASC),
  INDEX `fk_Caixas_has_Produtos_Caixas1_idx` (`comp_caix_id` ASC),
  INDEX `fk_Compras_Funcionarios1_idx` (`comp_func_id` ASC),
  CONSTRAINT `fk_Caixas_has_Produtos_Caixas1`
    FOREIGN KEY (`comp_caix_id`)
    REFERENCES `SCCE`.`Caixas` (`caix_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Caixas_has_Produtos_Produtos1`
    FOREIGN KEY (`comp_prod_id`)
    REFERENCES `SCCE`.`Produtos` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compras_Funcionarios1`
    FOREIGN KEY (`comp_func_id`)
    REFERENCES `SCCE`.`Funcionarios` (`func_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCCE`.`Modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE`.`Modulos` (
  `modu_id` INT NOT NULL AUTO_INCREMENT,
  `modu_nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`modu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCCE`.`Permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE`.`Permissoes` (
  `perm_grup_id` INT NOT NULL,
  `perm_modu_id` INT NOT NULL,
  PRIMARY KEY (`perm_grup_id`, `perm_modu_id`),
  INDEX `fk_Grupos_has_Modulos_Modulos1_idx` (`perm_modu_id` ASC),
  INDEX `fk_Grupos_has_Modulos_Grupos1_idx` (`perm_grup_id` ASC),
  CONSTRAINT `fk_Grupos_has_Modulos_Grupos1`
    FOREIGN KEY (`perm_grup_id`)
    REFERENCES `SCCE`.`Grupos` (`grup_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupos_has_Modulos_Modulos1`
    FOREIGN KEY (`perm_modu_id`)
    REFERENCES `SCCE`.`Modulos` (`modu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCCE`.`Movimentacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE`.`Movimentacoes` (
  `movi_func_id` INT NOT NULL,
  `movi_caix_id` INT NOT NULL,
  `movi_horario` DATETIME NOT NULL,
  `movi_valor` FLOAT NOT NULL,
  PRIMARY KEY (`movi_func_id`, `movi_caix_id`, `movi_horario`),
  INDEX `fk_Funcionarios_has_Caixas_Caixas2_idx` (`movi_caix_id` ASC),
  INDEX `fk_Funcionarios_has_Caixas_Funcionarios2_idx` (`movi_func_id` ASC),
  CONSTRAINT `fk_Funcionarios_has_Caixas_Funcionarios2`
    FOREIGN KEY (`movi_func_id`)
    REFERENCES `SCCE`.`Funcionarios` (`func_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionarios_has_Caixas_Caixas2`
    FOREIGN KEY (`movi_caix_id`)
    REFERENCES `SCCE`.`Caixas` (`caix_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCCE`.`Reposicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE`.`Reposicoes` (
  `repo_func_id` INT NOT NULL,
  `repo_prod_id` INT NOT NULL,
  `repo_horario` DATETIME NOT NULL,
  `repo_quantidade` INT NOT NULL,
  PRIMARY KEY (`repo_func_id`, `repo_prod_id`, `repo_horario`),
  INDEX `fk_Funcionarios_has_Produtos_Produtos1_idx` (`repo_prod_id` ASC),
  INDEX `fk_Funcionarios_has_Produtos_Funcionarios1_idx` (`repo_func_id` ASC),
  CONSTRAINT `fk_Funcionarios_has_Produtos_Funcionarios1`
    FOREIGN KEY (`repo_func_id`)
    REFERENCES `SCCE`.`Funcionarios` (`func_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionarios_has_Produtos_Produtos1`
    FOREIGN KEY (`repo_prod_id`)
    REFERENCES `SCCE`.`Produtos` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCCE`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE`.`Empresa` (
  `empr_nome` VARCHAR(45) NOT NULL,
  `empr_cnpj` VARCHAR(45) NOT NULL,
  `empr_endereco` VARCHAR(100) NOT NULL)
ENGINE = InnoDB
COMMENT = 'Apenas para guardar as informações da empresa. Por isso no singular, sem ligações com as demais tabelas e sem identificador por que deve conter apenas um registro. Garantir isso no programa.';

CREATE USER 'scce' IDENTIFIED BY '1234';

GRANT ALL ON `SCCE`.* TO 'scce';
GRANT SELECT ON TABLE `SCCE`.* TO 'scce';
GRANT SELECT, INSERT, TRIGGER ON TABLE `SCCE`.* TO 'scce';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `SCCE`.* TO 'scce';
GRANT EXECUTE ON ROUTINE `SCCE`.* TO 'scce';

insert into Caixas (caix_saldo) values (0);

insert into Grupos (grup_nome, grup_descricao) values ("Vendedor", "Funcionário que vende");
insert into Grupos (grup_nome, grup_descricao) values ("Operador de Caixa", "Funcionário que opera o caixa");

insert into Funcionarios (func_nome, func_salario, func_grup_id) values ("Baleeiro", 1000, 1);
insert into Funcionarios (func_nome, func_salario, func_grup_id) values ("Dominato", 1000, 2);


insert into Fabricantes (fabr_nome) values ("Unilever");
insert into Fabricantes (fabr_nome) values ("Nestle");
insert into Fabricantes (fabr_nome) values ("HP");
insert into Fabricantes (fabr_nome) values ("Dell");
insert into Fabricantes (fabr_nome) values ("Cimed");

insert into Produtos (prod_nome, prod_quantidade, prod_preco_compra, prod_preco_venda, prod_fabr_id) values ("Extrato de Tomate", 250, 1.50, 2.50, 1);
insert into Produtos (prod_nome, prod_quantidade, prod_preco_compra, prod_preco_venda, prod_fabr_id) values ("Caixa de Bombom", 200, 5.00, 9.00, 2);
insert into Produtos (prod_nome, prod_quantidade, prod_preco_compra, prod_preco_venda, prod_fabr_id) values ("Notebook", 250, 1000, 1500, 3);
insert into Produtos (prod_nome, prod_quantidade, prod_preco_compra, prod_preco_venda, prod_fabr_id) values ("Mouse", 250, 30, 50, 4);
insert into Produtos (prod_nome, prod_quantidade, prod_preco_compra, prod_preco_venda, prod_fabr_id) values ("Paracetamol", 100, 2.50, 5.00, 5);

insert into Compras values (1,1,1,1,NULL,NULL);
insert into Compras values (1,1,2,1,NULL,NULL);
insert into Compras values (1,1,4,1,NULL,NULL);
insert into Compras values (2,1,3,1,NULL,NULL);
insert into Compras values (2,1,5,1,NULL,NULL);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
