-- MySQL Script generated by MySQL Workbench
-- qui 22 jun 2017 23:58:50 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SCCE_BD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SCCE_BD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SCCE_BD` DEFAULT CHARACTER SET utf8 ;
USE `SCCE_BD` ;

-- -----------------------------------------------------
-- Table `SCCE_BD`.`Grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE_BD`.`Grupos` (
  `grup_id` INT NOT NULL AUTO_INCREMENT,
  `grup_nome` VARCHAR(45) NOT NULL,
  `grup_descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`grup_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCCE_BD`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE_BD`.`Funcionarios` (
  `func_id` INT NOT NULL AUTO_INCREMENT,
  `func_nome` VARCHAR(100) NOT NULL,
  `func_senha` VARCHAR(45) NOT NULL,
  `func_salario` FLOAT NOT NULL,
  `func_cate_id` INT NULL,
  PRIMARY KEY (`func_id`),
  INDEX `fk_Funcionarios_Categorias1_idx` (`func_cate_id` ASC),
  CONSTRAINT `fk_Funcionarios_Categorias1`
    FOREIGN KEY (`func_cate_id`)
    REFERENCES `SCCE_BD`.`Grupos` (`grup_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'A chave estrangeira não está como obrigatório porque a princípio não iremos implementar o layer em amarelo.';


-- -----------------------------------------------------
-- Table `SCCE_BD`.`Fabricantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE_BD`.`Fabricantes` (
  `fabr_id` INT NOT NULL AUTO_INCREMENT,
  `fabr_nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`fabr_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCCE_BD`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE_BD`.`Produtos` (
  `prod_id` INT NOT NULL AUTO_INCREMENT,
  `prod_nome` VARCHAR(100) NOT NULL,
  `prod_quantidade` INT NOT NULL DEFAULT 0,
  `prod_preco_compra` FLOAT NOT NULL,
  `prod_preco_venda` FLOAT NOT NULL,
  `prod_fabr_id` INT NOT NULL,
  PRIMARY KEY (`prod_id`),
  INDEX `fk_Produtos_Fabricantes_idx` (`prod_fabr_id` ASC),
  CONSTRAINT `fk_Produtos_Fabricantes`
    FOREIGN KEY (`prod_fabr_id`)
    REFERENCES `SCCE_BD`.`Fabricantes` (`fabr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCCE_BD`.`Caixas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE_BD`.`Caixas` (
  `caix_id` INT NOT NULL AUTO_INCREMENT,
  `caixa_saldo` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`caix_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCCE_BD`.`Turnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE_BD`.`Turnos` (
  `turn_func_id` INT NOT NULL,
  `turn_caix_id` INT NOT NULL,
  `turn_horario_inicio` DATETIME NOT NULL,
  `turn_horario_fim` DATETIME NULL,
  PRIMARY KEY (`turn_func_id`, `turn_caix_id`, `turn_horario_inicio`),
  INDEX `fk_Funcionarios_has_Caixas_Caixas1_idx` (`turn_caix_id` ASC),
  INDEX `fk_Funcionarios_has_Caixas_Funcionarios1_idx` (`turn_func_id` ASC),
  CONSTRAINT `fk_Funcionarios_has_Caixas_Funcionarios1`
    FOREIGN KEY (`turn_func_id`)
    REFERENCES `SCCE_BD`.`Funcionarios` (`func_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionarios_has_Caixas_Caixas1`
    FOREIGN KEY (`turn_caix_id`)
    REFERENCES `SCCE_BD`.`Caixas` (`caix_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCCE_BD`.`Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE_BD`.`Compras` (
  `comp_id` INT NOT NULL,
  `comp_caix_id` INT NOT NULL,
  `comp_prod_id` INT NOT NULL,
  `comp_qtd_produto` INT NOT NULL,
  `comp_horario` DATETIME NULL,
  PRIMARY KEY (`comp_id`, `comp_caix_id`, `comp_prod_id`),
  INDEX `fk_Caixas_has_Produtos_Produtos1_idx` (`comp_prod_id` ASC),
  INDEX `fk_Caixas_has_Produtos_Caixas1_idx` (`comp_caix_id` ASC),
  CONSTRAINT `fk_Caixas_has_Produtos_Caixas1`
    FOREIGN KEY (`comp_caix_id`)
    REFERENCES `SCCE_BD`.`Caixas` (`caix_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Caixas_has_Produtos_Produtos1`
    FOREIGN KEY (`comp_prod_id`)
    REFERENCES `SCCE_BD`.`Produtos` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCCE_BD`.`Modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE_BD`.`Modulos` (
  `modu_id` INT NOT NULL AUTO_INCREMENT,
  `modu_nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`modu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCCE_BD`.`Permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCCE_BD`.`Permissoes` (
  `perm_grup_id` INT NOT NULL,
  `perm_modu_id` INT NOT NULL,
  PRIMARY KEY (`perm_grup_id`, `perm_modu_id`),
  INDEX `fk_Grupos_has_Modulos_Modulos1_idx` (`perm_modu_id` ASC),
  INDEX `fk_Grupos_has_Modulos_Grupos1_idx` (`perm_grup_id` ASC),
  CONSTRAINT `fk_Grupos_has_Modulos_Grupos1`
    FOREIGN KEY (`perm_grup_id`)
    REFERENCES `SCCE_BD`.`Grupos` (`grup_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupos_has_Modulos_Modulos1`
    FOREIGN KEY (`perm_modu_id`)
    REFERENCES `SCCE_BD`.`Modulos` (`modu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
